// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupermarketAPI.Data;

#nullable disable

namespace SupermarketAPI.Migrations
{
    [DbContext(typeof(SupermarketContext))]
    [Migration("20251023015452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupermarketAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "7501234567890",
                            Category = "Lácteos",
                            CreatedAt = new DateTime(2025, 10, 23, 1, 54, 51, 287, DateTimeKind.Utc).AddTicks(5072),
                            Description = "Leche entera pasteurizada en envase de cartón de 1 litro",
                            IsActive = true,
                            Name = "Leche Entera 1L",
                            Price = 2.50m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2025, 10, 23, 1, 54, 51, 287, DateTimeKind.Utc).AddTicks(5219)
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7501234567891",
                            Category = "Panadería",
                            CreatedAt = new DateTime(2025, 10, 23, 1, 54, 51, 287, DateTimeKind.Utc).AddTicks(5467),
                            Description = "Pan de molde integral con semillas, 500g",
                            IsActive = true,
                            Name = "Pan de Molde Integral",
                            Price = 3.25m,
                            Stock = 25,
                            UpdatedAt = new DateTime(2025, 10, 23, 1, 54, 51, 287, DateTimeKind.Utc).AddTicks(5467)
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "7501234567892",
                            Category = "Frutas",
                            CreatedAt = new DateTime(2025, 10, 23, 1, 54, 51, 287, DateTimeKind.Utc).AddTicks(5469),
                            Description = "Manzanas rojas frescas, precio por kilogramo",
                            IsActive = true,
                            Name = "Manzanas Rojas (kg)",
                            Price = 4.80m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 10, 23, 1, 54, 51, 287, DateTimeKind.Utc).AddTicks(5470)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
